name: Flutter Web Deploy

on:
  push:
    branches:
      - bancolombia

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Build Flutter Web
        working-directory: cfd_flutter
        run: flutter build web --release --web-renderer html --base-href /cfd_flutter/
      - name: Configure git user
        working-directory: cfd_flutter
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Add changes to git
        working-directory: cfd_flutter
        run: git --work-tree build/web add --all
      - name: Commit changes
        working-directory: cfd_flutter
        run: git commit -m "Automatic deployment by github-actions"
      - name: Push to gh-pages
        working-directory: cfd_flutter
        run: git push origin HEAD:gh-pages --force
